version: '3.8'
services:
  app:
    volumes:
      - ..:/workspaces/nestjs-interview:cached
      - devcontainer_node_modules:/workspaces/nestjs-interview/node_modules
      - devcontainer_npm_cache:/home/node/.npm
    command: sleep infinity

volumes:
  devcontainer_node_modules:
  devcontainer_npm_cache:
